### PR TITLE
Metadat search

### PR DESCRIPTION
**Pull request by karissa**

### CODE REVIEW

**Comment by karissa** [comment]
@maxogden @mafintosh plz review!

**Comment by karissa** [comment]
now we just need to be able to search for multiple columns at once, @maxogden i think this might require changes to sqlite-search iirc

**Comment by maxogden** [comment]
@karissa hmm what would the SQL query look like to search multiple columns? can it have multiple `WHERE FOO MATCH 'BAR'` clauses?

**Comment by karissa** [comment]
@maxogden i was able to do it like this: https://github.com/karissa/dathub/commit/f71ab1c99ed7ca4cd2338f0159169d6b07d69d6b

**Comment by karissa** [comment]
why am i still getting a seg fault, though? I don't get it on my mac.

**Pull request merged**
